/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

int solver_01(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int solver_01_alloc_mem(void);
int solver_01_init_mem(int mem);
void solver_01_free_mem(int mem);
int solver_01_checkout(void);
void solver_01_release(int mem);
void solver_01_incref(void);
void solver_01_decref(void);
casadi_int solver_01_n_in(void);
casadi_int solver_01_n_out(void);
casadi_real solver_01_default_in(casadi_int i);
const char* solver_01_name_in(casadi_int i);
const char* solver_01_name_out(casadi_int i);
const casadi_int* solver_01_sparsity_in(casadi_int i);
const casadi_int* solver_01_sparsity_out(casadi_int i);
int solver_01_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int solver_01_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define solver_01_SZ_ARG 28
#define solver_01_SZ_RES 27
#define solver_01_SZ_IW 18
#define solver_01_SZ_W 980
#ifdef __cplusplus
} /* extern "C" */
#endif
